<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Configurations>Mono;Il2cpp</Configurations>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<RootNamespace>ExtraDrugs</RootNamespace>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Mono'">
		<TargetFramework>netstandard2.1</TargetFramework>
		<AssemblyName>ExtraDrugs_Mono</AssemblyName>
		<DefineConstants>$(DefineConstants);MONO;MONOMELON</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Il2cpp'">
		<TargetFramework>net6.0</TargetFramework>
		<AssemblyName>ExtraDrugs_Il2cpp</AssemblyName>
		<DefineConstants>$(DefineConstants);IL2CPP;IL2CPPMELON</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Assets\Models\crack_rock.glb" LogicalName="ExtraDrugs.Assets.Models.crack_rock.glb" />
	</ItemGroup>

	<PropertyGroup>
		<MonoPath>D:\Projects\Schedule I\Extra-Drugs\References\Mono</MonoPath>
		<Il2cppPath>D:\Projects\Schedule I\Extra-Drugs\References\Il2cpp</Il2cppPath>
	</PropertyGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Mono'">
		<Reference Include="0Harmony" HintPath="$(MonoPath)\0Harmony.dll" Private="false" />
		<Reference Include="Assembly-CSharp" HintPath="$(MonoPath)\Assembly-CSharp.dll" Private="false" />
		<Reference Include="MelonLoader" HintPath="$(MonoPath)\MelonLoader.dll" Private="false" />
		<Reference Include="S1API_Mono" HintPath="$(MonoPath)\S1API_Mono.dll" Private="false" />
		<Reference Include="S1MAPI_Mono" HintPath="$(MonoPath)\S1MAPI_Mono.dll" Private="false" />
		<Reference Include="ScheduleOne.Core" HintPath="$(MonoPath)\ScheduleOne.Core.dll" Private="false" />
		<Reference Include="UnityEngine.CoreModule" HintPath="$(MonoPath)\UnityEngine.CoreModule.dll" Private="false" />
		<Reference Include="UnityEngine" HintPath="$(MonoPath)\UnityEngine.dll" Private="false" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Il2cpp'">
		<Reference Include="0Harmony" HintPath="$(Il2cppPath)\0Harmony.dll" Private="false" />
		<Reference Include="Assembly-CSharp" HintPath="$(Il2cppPath)\Assembly-CSharp.dll" Private="false" />
		<Reference Include="Il2Cppmscorlib" HintPath="$(Il2cppPath)\Il2Cppmscorlib.dll" Private="false" />
		<Reference Include="Il2CppInterop.Runtime" HintPath="$(Il2cppPath)\Il2CppInterop.Runtime.dll" Private="false" />
		<Reference Include="Il2CppScheduleOne.Core" HintPath="$(Il2cppPath)\Il2CppScheduleOne.Core.dll" Private="false" />
		<Reference Include="MelonLoader" HintPath="$(Il2cppPath)\MelonLoader.dll" Private="false" />
		<Reference Include="S1API_Il2cpp" HintPath="$(Il2cppPath)\S1API_Il2cpp.dll" Private="false" />
		<Reference Include="S1MAPI_Il2cpp" HintPath="$(Il2cppPath)\S1MAPI_Il2cpp.dll" Private="false" />
		<Reference Include="UnityEngine.CoreModule" HintPath="$(Il2cppPath)\UnityEngine.CoreModule.dll" Private="false" />
		<Reference Include="UnityEngine" HintPath="$(Il2cppPath)\UnityEngine.dll" Private="false" />
	</ItemGroup>
</Project>